### ISSUE TITLE
Add guide for building a gem using Bundler 

### ISSUE THREAD

**Issue by indirect** [bundler/bundler-site#119]
Steal this guide: https://github.com/radar/guides/blob/master/gem-development.md

**Comment by EduardoBautista** [comment]
Looks like this still has not been added yet.  @radar are you OK with adding your guide to the site?  I will be making some edits such as removing the paragraph mentioning what Bundler is (we can assume that people browsing the Bundler site already know what it is).

**Comment by indirect** [comment]
Sounds great! :) Maybe you can also update for the new change of bin/ to exe/: http://bundler.io/blog/2015/03/20/moving-bins-to-exe.html

**Comment by radar** [comment]
Yes I would still be OK with adding my guide to the site. Please go ahead and take it :)

**Comment by EduardoBautista** [comment]
I will try to add this during the weekend.  I am currently traveling so I don't have much time right now.

**Comment by EduardoBautista** [comment]
I will be tracking the changes I will be making to the guide here: https://github.com/radar/guides/issues/67

Not many things to update at the moment, if you can think of anything else, leave a comment over there please!

**Comment by kruczjak** [comment]
Closed by #218 :)

http://bundler.io/v1.12/guides/creating_gem.html
