### ISSUE TITLE
Remove old versions from header

### ISSUE THREAD

**Issue by indirect** [bundler/bundler-site#138]
We've been very good about keeping Bundler stable since 1.0, and it seems like most people now use the latest stable version consistently. Let's continue to archive a copy of the docs as they were for each minor version, but move the list to a sidebar or another page rather than filling up the site header.

**Comment by EduardoBautista** [comment]
I can do this.  Just need to confirm whether the sidebar or a page called "archive" is ideal.

**Comment by indirect** [comment]
Let's add a single link named "older versions" or something like that, and then link to the docs for each version from there.

**Comment by EduardoBautista** [comment]
This can be closed now.
