### ISSUE TITLE
Add AppSignal to API sponsors page

### ISSUE THREAD

**Issue by indirect** [bundler/bundler-site#140]

**Comment by EduardoBautista** [comment]
I can do this if @andremedeiros is too busy.  I would just have to contact AppSignal for a logo unless you guys already have one.

**Comment by maclover7** [comment]
This should work, right?: https://shellycloud.com/assets/posts/2013-08-26-dependable-application-monitoring-with-app-signal/appsignal-logo-horizontal.png

**Comment by EduardoBautista** [comment]
@maclover7 Yeah, it looks fine.  I will try to add it later unless someone else wants to try.  I have a resized png here:

![index](https://cloud.githubusercontent.com/assets/1585126/6793329/a5535b84-d188-11e4-8e02-f25919188b20.png)
