### ISSUE TITLE
Strange margin-top on the .license class

### ISSUE THREAD

**Issue by heliocola** [bundler/bundler-site#175]
Hi there.
I noticed an strange (kinda unnecessary) margin-top in the .license class in http://bundler.io/conduct.html.

Scroll down to the License h3 element and inspect element.
There is a gap between the h3 and the p (which has the license class) caused by the margin-top in the license class.
See here: https://github.com/bundler/bundler-site/blob/master/source/stylesheets/application.scss#L499-L500

Is that meant to be like that? Not sure if it is some weird requirement for License sections.

If that is not, I can send the PR (https://github.com/heliocola/bundler-site/commit/1481f3caddd18416ca15a4180210aa949ad78cdf).

**Comment by indirect** [comment]
Sounds great. :+1:

**Comment by RochesterinNYC** [comment]
Closed by #176
