### ISSUE TITLE
Auto-deploy on commits to master

### ISSUE THREAD

**Issue by segiddins** [bundler/bundler-site#177]

**Comment by indirect** [comment]
:arrow_up: :boat:

**Comment by segiddins** [comment]
Related, maybe also set up heroku to build a new temporary site for each PR?

**Comment by indirect** [comment]
Oh man, what a good usecase for that feature.

**Comment by segiddins** [comment]
Heroic review apps are enabled.

**Comment by indirect** [comment]
Maybe we can have Travis run middleman and then push to the Github pages repo?

**Comment by segiddins** [comment]
yeah, the difficulty is being able to push securely

**Comment by segiddins** [comment]
(Also, the PR apps aren't working for some reason :( )

**Comment by indirect** [comment]
we can create a deploy key for Travis and put it in a secure env, so that seems easy. What's stuck on Heroku?

**Comment by segiddins** [comment]
@indirect not that simple, since you can't just use a key to push.
And heroku doesn't like my oauth token

**Comment by kruczjak** [comment]
I'll reassigne this to myself, because I'll start working on it tomorrow :)
I think, I'll do it using Travis and encrypted deployment key.
