### ISSUE TITLE
Links to documentation are broken

### ISSUE THREAD

**Issue by MatthiasWinkelmann** [bundler/bundler-site#178]
It appears that almost all links to the docs are broken. I.e. the [Homepage](http://bundler.io/) links to [http://bundler.io/v1.10/man/bundle.1.html](http://bundler.io/v1.10/man/bundle.1.html) which 404s. Many other links, such as almost all from [What's new](http://bundler.io/whats_new.html) also lead nowhere.

**Comment by indirect** [comment]
Oh no! This must be from the latest deploy. :( @segiddins I'm going to revert :/

**Comment by indirect** [comment]
http://bundler.io/v1.10/man/bundle.1.html no longer 404s. Thanks for reporting this!

**Comment by segiddins** [comment]
@rgb-one this is from deploying your changes. Can you please look into master ?
