### ISSUE TITLE
Rails 4 Guide

### ISSUE THREAD

**Issue by RochesterinNYC** [bundler/bundler-site#183]
Should there be a separate page for using Bundler with Rails 4? The latest one on the site is Rails 3 and the way that the Rails 2.3 and Rails 4 guides leaves it uncertain if the behavior for using bundler with Rails 4 would be the same as or different from Rails 3.

**Comment by indirect** [comment]
@RochesterinNYC I'm happy to add a page. The required steps are: nothing. `rails new` automatically runs `bundle install` after creating the Gemfile.

**Comment by kruczjak** [comment]
So, should I add such a page? :D

**Comment by hmistry** [comment]
Closing this issue. The Rails guide reflects the current way of using Bundler.
