### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by LynnCo** [bundler/bundler-site#199]
![bundler_blog](https://cloud.githubusercontent.com/assets/5768468/15129449/80105db4-15f6-11e6-8bcb-1317b0e770c8.png)
![bundler_homepage](https://cloud.githubusercontent.com/assets/5768468/15129450/8021f146-15f6-11e6-8cdc-0d992ec29c2e.png)
![bundler-site-header](https://cloud.githubusercontent.com/assets/5768468/15129451/802dc05c-15f6-11e6-82ee-6b2b3d9d5da9.png)

**Comment by kruczjak** [comment]
Closed by #218
