### ISSUE TITLE
Divide existing docs into Tutorials/Guides/Reference/Help sections

### ISSUE THREAD

**Issue by LynnCo** [bundler/bundler-site#203]
Tutorials: how to do a thing, like “create a gem with bundler”, or “work on an application and a gem it depends on at the same time”.

Guides: single topic deep dives, like “everything about git gems”, or “everything about gemfiles”.

Reference: exhaustive command reference, like “the bundle install command and every single flag and config option that impacts it”.

Help: how to get help and how to give help, so it should cover the [ISSUES](https://github.com/carlhuda/bundler/blob/master/ISSUES.md), CONTRIBUTING.md, and DEVELOPMENT.md files at least.

**Comment by kruczjak** [comment]
After #218, docs are divided into Tutorials, Guides and Reference

**Comment by indirect** [comment]
:tada:
