### ISSUE TITLE
execute the documentation code examples during the test suite

### ISSUE THREAD

**Issue by lynncyrin** [bundler/bundler-site#207]
the documentation (both the manpages/help and the website at bundler.io) contains many examples of running commands. we should run those examples as part of the test suite and make sure they work!

**Comment by esasse** [comment]
After some [discussion on Slack](https://bundler.slack.com/archives/C0ZRUQ78V/p1576326786001000) we decided to close old issues with ideas for improvement.

Please, feel free to reopen it if you intend to work on it in the foreseeable future.
