### ISSUE TITLE
Two comprehensive tutorials showing 1. how to use bundler when developing application (web, etc.) and 2. how to use bundler with gems.

### ISSUE THREAD

**Issue by LynnCo** [bundler/bundler-site#208]
This will illustrate the differences between the two ways bundler is used ie. for gem creation and when developing other types of applications like web applications and such.

 "Although apps and gems look like they share the concept of "dependency", there are some important differences between them. Gems depend on a name and version range, and intentionally don't care about where exactly the dependencies come from. Apps have more controlled deployments, and need a guarantee that the exact same code is used on all machines (dev, ci and production)."

**Comment by indirect** [comment]
This is done! Yay :tada:
