### ISSUE TITLE
Write a blog post about the redesign goals, and making the site easier to edit for casual contributors

### ISSUE THREAD

**Issue by lynncyrin** [bundler/bundler-site#210]

**Comment by LynnCo** [comment]
(IMO) The biggest issues being splitting the site into two repos (which isn't too complicated, but definitely barrier) - and having a folder with each version (which, I haven't figured out why that's a thing yet)

**Comment by esasse** [comment]
After some [discussion on Slack](https://bundler.slack.com/archives/C0ZRUQ78V/p1576326786001000) we decided to close old issues with ideas for improvement.

Please, feel free to reopen it if you intend to work on it in the foreseeable future.

**Comment by tnir** [comment]
#716 might be the first step for this. Any feedback to #716 is welcome! @coilysiren @esasse
