### ISSUE TITLE
Code of Conduct - page styling for readability

### ISSUE THREAD

**Issue by gusseting** [bundler/bundler-site#227]
The Code of Conduct page: http://bundler.io/conduct.html is currently without margins (at least, on a mac on chrome + firefox). It would be great to have this page conform to the rest of the site (eg blog: http://bundler.io/blog/, docs: http://bundler.io/docs.html) and be more readable.

**Comment by indirect** [comment]
whoa, good point. Thanks for opening this!

@kruczjak, could you put this page inside the normal template?
