### ISSUE TITLE
ISSUES troubleshooting guide

### ISSUE THREAD

**Issue by indirect** [bundler/bundler-site#237]
We should add the "Docs" layout to http://bundler.io/issues.html, and we should link to that page from the "Guides" list on the docs page, and the link should be named "Troubleshooting Guide".

**Comment by indirect** [comment]
@kruczjak any chance you'll be able to do this soon? I want to start linking people to bundler.io/issues.html instead of https://github.com/bundler/bundler/blob/master/ISSUES.md :sweat_smile:

**Comment by indirect** [comment]
oops you already fixed it sorry! thank you! 🙇

**Comment by kruczjak** [comment]
Closed by #231 :D
