### ISSUE TITLE
404 link on deploying.html to bundle-package man page

### ISSUE THREAD

**Issue by dentarg** [bundler/bundler-site#258]
On http://bundler.io/deploying.html "Learn More: Packing" links to http://bundler.io/bundle_package.html which returns 404, I guess the link should be: http://bundler.io/man/bundle-package.1.html

Not sure which document to edit in this repo, to fix it. Is it https://github.com/bundler/bundler-site/blob/master/source/v1.13/deploying.html.haml#L35? ([permalink](https://github.com/bundler/bundler-site/blob/127f961362483b4f111eebbfff2ac9de32942e09/source/v1.13/deploying.html.haml#L35))

**Comment by segiddins** [comment]
@kruczjak ?

**Comment by kruczjak** [comment]
@dentarg Yes, that one and you're correct with link :smile:

**Comment by dentarg** [comment]
I made a PR, but now I'm confused by the bundler website, as I found https://bundler.io/v1.13/deploying.html where the "Learn More: Packing" link do work (goes to https://bundler.io/v1.13/bundle_package.html)
