### ISSUE TITLE
Cleanup the styling for man/gemfile#platforms

### ISSUE THREAD

**Issue by lynnco** [bundler/bundler-site#260]
http://bundler.io/man/gemfile.5.html#PLATFORMS

It could stand to be less tightly formatted, and to move the entries

```
ruby_18
ruby AND version 1.8
```

onto a single line each

```
ruby_18 ruby AND version 1.8
```

**Comment by lynnco** [comment]
That file actually exists in bundler/bundler https://github.com/bundler/bundler/blob/master/man/gemfile.5.ronn

**Comment by feministy** [comment]
i got this!
