### ISSUE TITLE
Generate man pages from `bundle $COMMAND --help`

### ISSUE THREAD

**Issue by lynncyrin** [bundler/bundler-site#263]
So that instead of having a [separate file](https://github.com/bundler/bundler-site/blob/master/source/v1.13/bundle_clean.html.haml) in this repo for the command, [the page](http://bundler.io/v1.13/bundle_clean.html) gets generated from [the output](https://github.com/bundler/bundler/blob/c3b69668529ff9bbdd923f89fd0758418998dc37/lib/bundler/cli.rb#L418-L426) of `bundle $COMMAND --help`

**Comment by indirect** [comment]
This is done! Hooray.
