### ISSUE TITLE
Use Bundler with Rails 3, Rails 2.3 links dead

### ISSUE THREAD

**Issue by duckinator** [bundler/bundler-site#272]
On https://bundler.io/docs.html, the "Rails 3" and "Rails 2.3" links under "Use Bundler with" return 404s.

Also, https://bundler.io/v1.13/rails.html exists but is never linked to from that page.

**Comment by lynnco** [comment]
Ah, this was from https://github.com/bundler/bundler-site/pull/257 :( should have reviewed it more thoroughly.

cc @colby-swandale

**Comment by lynnco** [comment]
Oh! https://github.com/bundler/bundler-site/pull/270

**Comment by colby-swandale** [comment]
#270 was merged which fixes this issue, @lynnco can you please close.
