### ISSUE TITLE
http://bundler.io/bundle_gem.html gets sent to a "Page not found"

### ISSUE THREAD

**Issue by jks8787** [bundler/bundler-site#294]
Hi!

I really like bundler, and the site http://bundler.io/ is really helpful! thanks for that!

the issue is when you start from http://bundler.io/v1.12/#getting-started

then click the button about making your own gem `Learn More: bundle gem`

you are take to http://bundler.io/bundle_gem.html  which has no content on it :(

it looks like there should be content for this page ( based on the code )
https://github.com/bundler/bundler-site/blob/master/source/v1.11/bundle_gem.html.haml

**Comment by segiddins** [comment]
That's odd, since http://bundler.io/v1.14/man/bundle-gem.1.html does exist.... thanks for the bug report!

**Comment by theoretick** [comment]
Looks like v1.11 had a [bundle_gem.html.haml](https://github.com/bundler/bundler-site/blob/master/source/v1.11/bundle_gem.html.haml), but 1.12 forward does not. Should that page be added or should index be updated to point at `./man/bundle-gem.1.html` instead?

**Comment by segiddins** [comment]
I don't know... @indirect ?

**Comment by indirect** [comment]
point to the man page now 👍
