### ISSUE TITLE
Bug: bundle-gem man page "See also" link should point to the right page

### ISSUE THREAD

**Issue by olleolleolle** [bundler/bundler-site#296]
Generated HTML link to "See also" content which appears on the bundle-gem man page has the wrong shape.

Example:

At the bottom of the page http://bundler.io/v1.14/bundle_gem.html we have the following:

- Desired: `http://bundler.io/v1.14/bundle_config.html` (which exists)
- Current: `http://bundler.io/v1.14/bundle-config.html` (which does not exist)

**Comment by olleolleolle** [comment]
Turns out, that page was the  only one of Bundler's `man/` pages that had a section of SEE ALSO that pointed to another page of content.

**Comment by arbonap** [comment]
👋🏽 I'd be happy to tackle this issue, if no one else would like to claim it.

**Comment by segiddins** [comment]
@arbonap go for it!
