### ISSUE TITLE
canonical meta to Reference pages

### ISSUE THREAD

**Issue by beijaflor** [bundler/bundler-site#308]
![screen shot 2017-06-09 at 19 52 13](https://user-images.githubusercontent.com/1697419/26972571-5816f220-4d4d-11e7-8997-8b1779354b03.png)

Today I googled with term `bundle config` and got v1.3 version of the document.
It might be better index only newest version of References to Google ( even other search engine ), right?

To do so, add `<link rel="canonical" href="https://bundler.io/man/bundle-config.1.html">` inside `<head>` tag to all other version of pages.

**Comment by colby-swandale** [comment]
A PR to help address this issue would be super appreciated 👍

**Comment by beijaflor** [comment]
@colby-swandale 
Yes, I will
