### ISSUE TITLE
Broken links in docs

### ISSUE THREAD

**Issue by bobwhitelock** [bundler/bundler-site#314]
Hi - if I go to https://bundler.io/v1.15/gemfile.html, or any of the other guides, I get a 404 when I click on any of the links to other guides on the left. Also possibly related, only 3 guides appear here but a lot more are shown on [the main docs page](https://bundler.io/docs.html). Thanks.

**Comment by colby-swandale** [comment]
Thanks for reporting this issue, we'll this fixed.
