### ISSUE TITLE
Links to other ronn-created pages are not rendered

### ISSUE THREAD

**Issue by olleolleolle** [bundler/bundler-site#355]
One of the things in the documentation which is not working right now is how links to other pages are rendered.

- `Gemfile(5)` is rendered as a link http://bundler.io/v1.16/man/bundle-update.1.html
- `bundle package` is not http://bundler.io/v1.16/man/bundle-package.1.html#REMOTE-FETCHING

In addition, the man pages now also have Markdown residue in them:

<img width="807" alt="image" src="https://user-images.githubusercontent.com/211/34483192-2739cf66-efbd-11e7-9543-6bfc5461d638.png">

**Comment by segiddins** [comment]
https://github.com/bundler/bundler/pull/6244 should fix this!
