### ISSUE TITLE
Add documentation for `glob` to "How to install gems from git repositories" page

### ISSUE THREAD

**Issue by tcdowney** [bundler/bundler-site#372]
Hello!

Recently I needed to install a gem from a Git repository, but the gem was nested within a subdirectory of the repository. Looking at the [existing docs](http://bundler.io/guides/git.html) I couldn't find anything that would allow me to do this. I eventually found an issue that mentioned the `glob` parameter and it worked, but it would be nice if this was documented more explicitly.

For example, in order to install [this gem](https://github.com/cloudfoundry/copilot/tree/master/sdk/ruby) from its Git source, I can use `glob` like this:
```
gem 'cf-copilot', git: 'https://github.com/cloudfoundry/copilot.git', branch: 'master', glob: 'sdk/ruby/*.gemspec'
```

Thanks!

**Comment by rubymorillo** [comment]
thanks @tcdowney! would you like to open up a PR in the doc to have that added in? https://github.com/bundler/bundler-site/blob/master/source/v1.16/guides/git.html.haml

**Comment by tcdowney** [comment]
Thanks for merging the PR!
