### ISSUE TITLE
Add footer to all Bundler docs pages to encourage contributors to edit

### ISSUE THREAD

**Issue by rubymorillo** [bundler/bundler-site#376]
Hey team,

I've been working with @indirect on a list of items for the Bundler Docs site and one of them was to have a footer appear at the bottom of all of the docs pages (man pages, guides) to encourage folks to contribute to the documentation if they've spotted something that's not there, or if they've noticed the error. The hope is it'll encourage more people to add to our documentation and remove blockers to updating docs (especially if it's something that we haven't noticed).

As an example, here's how that looks like in Vue.js' docs site:
![footer](https://user-images.githubusercontent.com/3386562/39637407-dffe7366-4f90-11e8-9fb6-c3778539a600.png)

And each page links out to the corresponding file in the GitHub repo.

I did this at the bottom of the [SSL troubleshooting guide](http://bundler.io/v1.16/guides/rubygems_tls_ssl_troubleshooting_guide.html) I wrote last year, but I'd like to see this done seamlessly across all of our pages.

Here's the copy I have so far:

---
>
### Contributing to this guide
>[Edit this document in GitHub](#) if you caught an error or noticed something was missing. 
---

I need help from someone to actually implement this on the Bundler site. Would someone be able to assist? Language suggestions welcome

cc @segiddins @indirect @colby-swandale

**Comment by segiddins** [comment]
Looks great! Just a note that for guides / doc pages that come from the Bundler repo, well want to link to the original source rather than the one in the site repo

**Comment by rubymorillo** [comment]
Gotcha! I hate to ask someone to actually build out the logic and test how it would look on the site, but that's not my strength 😄 Is that something you could help out with at some point, @segiddins?

**Comment by segiddins** [comment]
I probably could!

**Comment by rubymorillo** [comment]
that's be awesome @segiddins 🙏
