### ISSUE TITLE
Add a page discussing ways to use Bundler with Docker

### ISSUE THREAD

**Issue by indirect** [bundler/bundler-site#386]
Based on bundler/bundler#6524, it looks like the Docker default images for Ruby have cleverly engineered a situation where only one bundle and one application can exist inside the docker container.

For users who want to have more than one Gemfile, or simply install gems via RubyGems and use them as system gems, this situation is confusing, and has historically led to a lot of bug reports and even pull request against Bundler.

Instead, we want to document how Bundler handles binstubs, document how the default Docker Ruby image handles binstubs, and then document how the user can configure Bundler within Docker to support whatever setup it is that they want.

More details about those situations can be found in the comments on the ticket linked above.

**Comment by rubymorillo** [comment]
@indirect 👋 I'll start working on a draft this week
