### ISSUE TITLE
Optional Groups Are Completely Undocumented (Except the Release Notes)

### ISSUE THREAD

**Issue by Dakta** [bundler/bundler-site#393]
Except for [the v1.10 release notes](https://bundler.io/v1.10/whats_new.html), Bundler's documentation makes no mention whatsoever of the optional groups feature added in that version. Particularly frustrating, it is not even mentioned on [the Groups guide](https://bundler.io/v1.16/guides/groups.html) in any version. Look in https://github.com/bundler/bundler-site/blob/master/source/v1.16/guides/groups.html.haml, no mention of "optional".

This is frustrating, as optional groups are a very useful feature for making conditional deployments easy. Having to always remember to specify `--without` was extremely clumsy when the majority of deployments would not use a specific group.

**Comment by rubymorillo** [comment]
Thanks for pointing it out, @Dakta; we'll get this added to the Groups guide.
