### ISSUE TITLE
Include Examples 

### ISSUE THREAD

**Issue by jendiamond** [bundler/bundler-site#56]
This can probably be deleted or just included in the other issue:
Generate pages for each command from the manpages

http://bundler.io/v1.3/bundle_install.html#no-cache

**Add Examples for each of these:**

- [ ] Example with --binstubs
- [ ] Example with --clean
- [ ] Example with --frozen
- [ ] Example with --full-index
- [ ] Example with --gemfile
- [ ] Example with --local
- [ ] Example with --no-cache
- [ ] Example with --no-prune
- [ ] Example with --quiet
- [ ] Example with --shebang
- [ ] Example with --standalone
- [ ] Example with --system

http://bundler.io/v1.3/bundle_open.html

- [ ] bundle open Detailed description 
- [ ] bundleopen Example with default options

**Comment by rgb-one** [comment]
Is this still relevant?

**Comment by indirect** [comment]
Nah, I think this is covered by other tickets now.
